SELECT 
CONVERT(INT, CO.COLID) AS Id,
TB.NAME AS SqlTableName,
CO.NAME AS SqlColumnName, 
SA.DESCR AS SapDescription,
TY.NAME AS SqlDataType,
SA.TYPEID AS SapDataType,
SA.EDITTYPE AS SapDataType2,
CONVERT(INT, ISNULL(CO.PREC, 0)) AS SqlSize, 
CONVERT(INT, CO.XSCALE) AS SqlPrecision, 
CO.ISNULLABLE AS NullValue
FROM DBO.SYSCOLUMNS CO
INNER JOIN DBO.SYSOBJECTS TB ON CO.ID = TB.ID
INNER JOIN DBO.SYSTYPES TY ON CO.XTYPE = TY.XUSERTYPE
LEFT JOIN CUFD SA ON TB.NAME = SA.TABLEID AND CO.NAME = 'U_' + SA.ALIASID
WHERE
CO.NAME <> 'Name' AND
TB.NAME = ?